# Exported from Render on 2024-09-30T05:48:34Z
services:
- type: web
  name: Discord-Pyron-Bot-1
  runtime: python
  repo: https://github.com/levox00/Discord-Pyron-Bot
  branch: Test
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  - key: DISCORD_TOKEN
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
version: "1"
